### ISSUE TITLE
Upgrade webpack encore

### ISSUE THREAD

**Issue by respinoza** [moay/server-for-symfony-flex#28]
The current version is 0.17, latest is 0.27 and a lot of improvements has been done js wise, also with this upgrade we reduce the vulnerable packages from ~220 to 1 (tar, in the works).

Finally this also brings some twig helpers and config that makes integrating encore easier.

**Comment by moay** [comment]
Hi @respinoza 

Thanks for the pr. Sorry, but I don't see the need for the webpack bundle. There is actually very little frontend stuff here, so we don't need any big improvements there?

Updating encore itself is a good idea. As the tar issue seems to be the only critical one, I'll wait for it to be resolved for a major update on the frontend vendors.

**Comment by respinoza** [comment]
@moay that's actually the upgrade path as per this post https://symfony.com/blog/encore-0-21-0-webpack-4-support-copy-files-support-webpackencorebundle
So at some point it has to be done.
Once you decide to upgrade let me know and I'll rebase te PR in the future.
As a side note, we already did this in our deployment as we changed a bit the frontend.

Cheers

**Comment by moay** [comment]
Thanks for the hint, I was not aware of the pack being deprecated. Switching to the bundle seems less useless then. ;-)

I'll look into it when I find the time

**Comment by SebTM** [comment]
Can you reopen the pull-request to not forget it? I also tested it and beside some javascript packages which need to be updated everything looks good :)

**Comment by moay** [comment]
Done
