### ISSUE TITLE
Name of the repository

### ISSUE THREAD

**Issue by fabpot** [moay/server-for-symfony-flex#34]
Hi,

I stumbled upon this repository by chance and I think there is an issue with the name. By using Symfony Flex Server, people might think that this is an official Symfony project, which it is not. So, can you please rename the project to something else that does not contain Symfony?

Thank you.

**Comment by moay** [comment]
Hi

thanks for getting in touch. I already thought about the name of the project and we had some discussions on that. Having Symfony in the name seems legit to me, as the project's main focus is to provide a self hosted server for Symfony flex. Additionally, changing the repo's url might confuse people who use the project by now.

In order to help people recognizing the project as a non-official project, we decided to not include the Symfony logo, but we could certainly state that more clearly. It's an important information regarding reliability and 'bullet-proofness'. I'll add a prominent note to the main readme and to the documentation.

**Comment by fabpot** [comment]
You cannot use "Symfony" in your project name without permission. Please, change it.

**Comment by moay** [comment]
Done. I also changed the project's name in the main headline. Is that what you meant?

**Comment by fabpot** [comment]
To be clear, the Symfony name cannot be used for this project. The project repository name, the headline and the main title in the description are all using Symfony (which might make people think that this is an official Symfony project).

See https://symfony.com/trademark for more information.

**Comment by moay** [comment]
Ah, ok. Didn't see this page before. I'll of course act according to the official rules and change the names.

Stating from the page you linked:

```
Permitted use of the Trademarks

Certain usages of the Trademarks are fine and no specific permission from us is needed.

(...)

Building on Symfony or for Symfony. 

If you are producing new software which is intended for use with or on Symfony, you may use the Trademark in a way which indicates the intent of your product. For example, if you are developing a system management tool for Symfony, acceptable project titles would be "System Management for Symfony" or "Symfony Based Systems Management". We would strongly discourage, and likely would consider to be problematic, a name such as SymfonyMan, Symfony Management, SymfoMan, etc. Furthermore, you may not use the Trademarks in a way which implies an endorsement where that doesn't exist, or which attempts to unfairly or confusingly capitalise on the goodwill or brand of the project.
```

That's the section you are referring to, right? I'll of course change everything (including repo name and headlines) to 'server for Symfony Flex', ligning up with the trademark guidelines.

**Comment by nicolas-grekas** [comment]
There is also:

>  Use of a name which includes the letters SYMF or SF in relation to a PHP Open-Source project;

So my understanding is that the *name* cannot contain "Symfony", but a oneliner description (title) can mention "server for Symfony Flex" (provided the other provisions are respected of course).

**Comment by moay** [comment]
That strongly interferes with

> If you are producing new software which is intended for use with or on Symfony, you may use the Trademark in a way which indicates the intent of your product. For example, if you are developing a system management tool for Symfony, acceptable project titles would be "System Management for Symfony" or "Symfony Based Systems Management".

The repo name is mainly just a slugified representation of the project's title. 'Project title' or 'name' are used completely synonymously in general language (to me, a oneliner description would be a 'description').

**Comment by moay** [comment]
The name `symfony-flex-server` has been replaced with `server-for-symfony-flex` everywhere in the project. Let me know if I missed a spot.
