### ISSUE TITLE
Recipes in Bitbucket Server

### ISSUE THREAD

**Issue by keldrox** [moay/server-for-symfony-flex#44]
Hello,

I would like to ask if it is possible to run the server-for-symfony-flex package with Bitbucket Server, this does not work for me

Regards!

**Comment by moay** [comment]
Hi there,

should actually work, works for bitbucket repos for me and also for selfhosted gitlab. So neither selfhosting nor bitbucket should be a problem.

What exactly doesn't work? Make sure to double check your repo url (see https://server-for-symfony-flex.readthedocs.io/en/latest/topics/configuration/#private-recipes-repo)

> Github has proven to be quite good in resolving git requests, other providers or git servers may be pickier. If you run into problems, try to play with '.git', the protocol prefix or the type of url provided.

Also make sure that your repo is available for the server.

**Comment by keldrox** [comment]
I'm going to start with the easy with Github,

I have my recipes: https://github.com/keldrox/symfony-recipes

My server-for-symfony-flex server has configured in the .env file FLEX_RECIPE_REPO_PRIVATE = https: //github.com/keldrox/symfony-recipes

Performed the command "php bin / console recipes: reset"

All OK: [https://ibb.co/KrMygyt](url)

In my Symfony project I edit the composer.json file and add
"symfony": {
         "endpoint": "XXXX"
     },

I execute "composer require keldrox / demo-bundle" but it is not found

What can happen?

Thank you!

**Comment by moay** [comment]
I think there might be a slight understanding in what Flex is supposed to do here. Symfony Flex does not server your bundles to composer, it just enriches them by using recipes. That means: Your bundle needs to be published on packagist (or some private clone) in order to be able to install it using composer. Make sure to check this with a package that exists.

**Comment by keldrox** [comment]
Thanks again moay.

Exactly using the package with Packagist works. But my packages are in a private bitbucket server. In this case how could I proceed?
I think I'm missing the composer connection with my private packages on Bitbucket Server, but I don't know how to proceed

Thank you!

**Comment by moay** [comment]
You'll have to either host some sort of private packagist (use https://packagist.com, the official open source https://github.com/composer/packagist/, https://github.com/lukaszlach/satis-server or any other available tool for that) or map your package directly to your repo (good explanation here: https://barryvanveen.nl/blog/55-installing-a-private-package-with-composer). Either way there seems not to be an issue with the flex server, I'll therefore close this.
