### ISSUE TITLE
Issue with static assets

### ISSUE THREAD

**Issue by thasmo** [moay/server-for-symfony-flex#46]
It seems that in 79b1e4d606a4b2de58c000c98954aa5365c22525 changes were made in the `.gitignore` file which lead to a erroneuos state of the commited static assets; most files are missing and the manifest file differs from a real production build as in the mapped filenames do not include a hash.

Due to this there was a Twig error after deploying the latest version, because Twig `asset` can not find the files listed in the manifest.

This issue actually breaks the latest build.

We added `!/public/build/` to the `.gitignore` file in our private fork, built the assets via `npm run build` and commited the whole `public/build/` directory.

**Comment by thasmo** [comment]
Otherwise, if `public/build/` should not be commited it would be needed to document how to build the webpack bundle while deploying the application.

**Comment by c33s** [comment]
`public/build/` should not be in the repository. its like `vendor` which also gets pulled with `composer install` and are not in the repo.

how to use and build assets is documented on https://symfony.com/doc/current/frontend.html

mainly its only running:
```
yarn install
yarn run encore dev
```

**Comment by thasmo** [comment]
@c33s, created a new PR.
