### ISSUE TITLE
local recipes title loaded wrong

### ISSUE THREAD

**Issue by mahsamnz** [moay/server-for-symfony-flex#55]
@moay why the directory names (private - official - contrib) loaded here ?

![bug](https://user-images.githubusercontent.com/45381547/81282110-fbe3c780-906f-11ea-8104-57b7d8984828.PNG)

**Comment by moay** [comment]
Hu, thats strange. maybe thats related to the change of the base flex server from symfony.sh to flex.symfony.com. I'll see if I can replicate this.

**Comment by mahsamnz** [comment]
I think the problem is related to windows! some directories seprated by \ 
I change the code from
$explodedPath = explode('/', $recipeFolder->getPathname());
to
$explodedPath = explode('/', strtr($recipeFolder->getPathname(), '\\', '/'));
and fix it
