### ISSUE TITLE
problem with copy-from-recipe

### ISSUE THREAD

**Issue by mahsamnz** [moay/server-for-symfony-flex#56]
@moay this is my recipe repo : https://github.com/mahsamnz/demo-recipes

I expect bugloos-api-form.yaml file added to config/routes directory in my base project after composer install but nothing added.

what is the problem? am I write anything wrong?

**Comment by moay** [comment]
Sorry, late reply. I'm not completely certain, but I think Flex will never override anything. So as there already is a `/config` folder in your project, it won't copy the folder from the recipe. You'll want to change this: 

```
  "copy-from-recipe": {
    "config/": "%CONFIG_DIR%/"
  },
```
to this:

```
  "copy-from-recipe": {
    "config/routes/bugloos-api-form.yaml": "%CONFIG_DIR%/routes/bugloos-api-form.yaml"
  },
```

Let me know if this helps.

**Comment by kl3sk** [comment]
I can confirm that @moay solution works.
