### ISSUE TITLE
php7.3 Browser access error after startup. But other uses are normal.

### ISSUE THREAD

**Issue by CJayHe** [moay/server-for-symfony-flex#66]
![截屏2021-04-2317 11 13](https://user-images.githubusercontent.com/22066314/115848916-f5a05400-a456-11eb-953f-238f87bf1ad4.png)

**Comment by moay** [comment]
Please ask questions in English.

Looks like you didn't build the assets properly. Rebuild them if needed.

**Comment by CJayHe** [comment]
![截屏2021-04-2509 50 46](https://user-images.githubusercontent.com/22066314/115977542-d5ce7480-a5ab-11eb-89f0-e278a3152ea9.png)
Or not！

**Comment by moay** [comment]
That's not how you compile assets. :)

Try

```
npm install
npm run build
```
--
